repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: end-of-file-fixer
      - id: check-ast
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/sqlalchemyorg/zimports/
    rev: 0.1.3
    hooks:
    -   id: zimports
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
        args: ["--line-length", "120", "-S"]
