[tool.poetry]
name = "slitherlinker"
version = "0.1.0"
description = "Solve slitherlink puzzles"
authors = ["Oleksandr Podze <dasdeg@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10,<3.12"
# opencv-python = "^4.4.0"
# matplotlib = "^3.3.1"
# scikit-image = "^0.17.2"
# imutils = "^0.5.3"
# tensorflow = "^2.3.0"
# click = "^7.1.2"
# Pillow = "^7.2.0"

# [tool.poetry.dev-dependencies]
# jupyterlab = "^2.2.7"
# tqdm = "^4.48.2"
cython = "^0.29.35"
opencv-python = "^4.7.0.72"
matplotlib = "^3.7.1"
scikit-image = "^0.21.0"
imutils = "^0.5.4"
tensorflow = "^2.12.0"
click = "^8.1.3"
pillow = "^9.5.0"
jupyterlab = "^4.0.1"
tqdm = "^4.65.0"


[build-system]
requires = ["poetry>=1"]
build-backend = "poetry.masonry.api"